const router = require("express").Router()
const auth = require("../app/middleware/auth")
const Admin = require("../app/middleware/admin")
const userController =  require("../app/controller/user.controller")
router.post("/register", userController.register)
router.get("/all", userController.all)
router.get("/all/:id", userController.singleUser)
router.patch("/all/editPass/:id", userController.editPass)
router.post("/login", userController.login)
router.get("/me", auth, userController.me)
router.delete("/all/:id", userController.deleteUser)
router.patch("/all/:id", Admin ,userController.editUser)
router.patch("/all/editPass/:id",auth, userController.editPass)
router.post("/logout", auth, userController.logout)
router.post("/logoutAll", auth, userController.logoutAll)
router.patch("/changeStatus", auth, userController.changeStatus)
router.delete("/delMe", auth, userController.delMe)
const multer  = require('multer')
const upload = multer({ dest: 'public/' })
router.post('/profile',auth ,upload.single('img'),  userController.imgUpload)
module.exports = router